version: '3'

services:
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8501:8501
    networks:
      - deploy_network
    container_name: streamlit_app
    volumes:
      - ./storage:/storage

networks:
  deploy_network:
    driver: bridge
