name: Deploy to Google Cloud

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check-out your repository.
      - name: Checkout
        uses: actions/checkout@v2

      # Authenticate with Google Cloud
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials: ${{ secrets.GOOGLE_CLOUD_CREDENTIALS }}

      # Configure Docker
      - name: Configure Docker
        uses: docker/setup-buildx-action@v1

      # Build and Push Docker container
      - name: Build and Push Docker container
        uses: docker/build-push-action@v2
        with:
          context: ./
          push: true
          tags: gcr.io/${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}/ml-model:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: google-actions/gcloud-run@v1
        with:
          args: deploy ml-model --image gcr.io/${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}/ml-model:latest
