name: Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: YOUR_PROJECT_ID
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: gcr.io/$GOOGLE_CLOUD_PROJECT/your-app:${{ github.sha }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@main
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          image: gcr.io/$GOOGLE_CLOUD_PROJECT/your-app:${{ github.sha }}
          region: YOUR_REGION
          service_name: your-app
          platform: managed
